# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vagrant.plugins = "vagrant-vbguest"
  config.vagrant.plugins = "vagrant-bindfs"
  config.vagrant.plugins = "vagrant-share"
  config.vm.box = 'generic/ubuntu1804'

  config.vm.box_check_update = false

  config.vm.define "idea" do |idea|

  idea.vm.host_name = 'idea'
  idea.ssh.username =$user
  idea.ssh.password =$user
   idea.vm.network 'forwarded_port', guest: 22,   host: 2170, id: 'ssh', auto_correct: true

  idea.vm.box = "ookk3388/baseidea"
  idea.vm.host_name = 'idea-dev'

  idea.vm.network "private_network", ip: "192.168.99.200"
 #配置当前vm的host-only网络的IP地址为192.168.33.10
  idea.vm.network "public_network", ip: "192.168.0.200" , bridge: "en3: Wi-Fi (AirPort)"
 #创建一个bridge桥接网络，指定IP




  idea.vm.synced_folder "~/", "/home/user",type: "rsync"
 # Use vagrant-bindfs to re-mount folder
 #config.bindfs.bind_folder "/vagrant-nfs", "guest/mount/point"

 # Bind a folder after provisioning
 #config.bindfs.bind_folder "/vagrant-after-provision", "another/guest/mount/point", after: :provision
  idea.vm.synced_folder  '/volumes/disk', '/home/disk', type: :nfs
  idea.vm.synced_folder '/volumes/b','/home/b', type: :nfs
  idea.vm.synced_folder "/volumes/runtime","/home/runtime", type: :nfs

  idea.vm.synced_folder '../', '/home/vagrant',type: "rsync"

  idea.vm.provider 'virtualbox' do |vb|
    vb.gui = true
    vb.name = 'idea'
    vb.memory = 2048
    vb.cpus = 2
    vb.customize ['modifyvm', :id, '--vram', '256']

    vb.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
    vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]


    vb.customize ["modifyvm", :id, "--rtcuseutc", "on"]
    vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
    vb.customize ["modifyvm", :id, "--nestedpaging", "on"]
    vb.customize ["modifyvm", :id, "--vtxvpid", "on"]
    vb.customize ["modifyvm", :id, "--largepages", "on"]
    vb.customize ["modifyvm", :id, "--acpi", "on"]
    vb.customize ["modifyvm", :id, "--groups", "/idea开发"]

    # change the network card hardware for better performance
    vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
    vb.customize ["modifyvm", :id, "--nictype2", "virtio"]

    # suggested fix for slow network performance
    # see https://github.com/mitchellh/vagrant/issues/1807



    vb.customize ['modifyvm', :id, '--accelerate2dvideo', 'off']
    vb.customize ['modifyvm', :id, '--accelerate3d', 'on']
    #用高清显示
   # vb.customize ['setextradata', :id, 'GUI/HiDPI/UnscaledOutput', '1']

  end

  # Copy private key to VM for Git and other tools
 idea.vm.provision 'file', source: "#{ENV['HOME']}/.ssh/id_rsa", destination: '~/.ssh/id_rsa'
  idea.vm.provision 'shell', privileged: false, path: 'provision/base.sh', name: 'base.sh'
  idea.vm.provision 'shell', privileged: false, path: 'provision/deb.sh', name: 'deb.sh'
  idea.vm.provision 'shell', privileged: false, path: 'provision/git.sh', name: 'git.sh'
  idea.vm.provision 'shell', privileged: false, path: 'provision/xfce4.sh', name: 'xfce4.sh'
  idea.vm.provision 'shell', privileged: false, path: 'provision/apps.sh', name: 'apps.sh'
 # idea.vm.provision 'shell', privileged: false, path: 'provision/google-chrome.sh', name: 'google-chrome.sh'
  idea.vm.provision 'shell', privileged: false, path: 'provision/java.sh', name: 'java.sh'
 # idea.vm.provision 'shell', privileged: false, path: 'provision/idea.sh', name: 'idea.sh'
  idea.vm.provision 'shell', privileged: false, path: 'provision/nodejs.sh', name: 'nodejs.sh'
  idea.vm.provision 'shell', privileged: false, path: 'provision/nvm.sh', name: 'nvm.sh'
  idea.vm.provision 'shell', privileged: false, path: 'provision/atom.sh', name: 'atom.sh'
  idea.vm.provision 'shell', privileged: false, path: 'provision/vim.sh', name: 'vim.sh'
  idea.vm.provision 'shell', privileged: false, path: 'provision/fonts.sh', name: 'fonts.sh'
  idea.vm.provision 'shell', privileged: false, path: 'provision/docker.sh', name: 'docker.sh'
  idea.vm.provision 'shell', privileged: false, path: 'provision/aws.sh', name: 'aws.sh'
  idea.vm.provision 'shell', privileged: false, path: 'provision/zh.sh', name: 'zh.sh'
  idea.vm.provision 'shell', privileged: false, path: 'provision/local.sh', name: 'local.sh'






    idea.vm.provision 'shell', privileged: false, path: 'provision/dev.sh', name: 'dev.sh'
  end
end
